const CAP_TITLES=["","Commander","Vice Commander","Deputy Commander","Deputy Commander for Cadets","Deputy Commander for Seniors","Chief of Staff","Executive Officer","Command Chief Master Sergeant","NCO Advisor","Administrative Officer","Personnel Officer","Professional Development / Education & Training Officer","Historian","Inspector General","Equal Opportunity Officer","Testing Officer","Recruiting & Retention Officer","Cadet Programs Officer","Cadet Activities Officer","Leadership Education Officer","Aerospace Education Officer","Character Development Instructor (CDI)","Chaplain","Fitness Officer","Cadet Programs Development Officer","Cadet Cyber Education Officer","Emergency Services Officer","Operations Officer","Standardization/Evaluation Officer","Plans and Programs Officer","Air Operations Branch Director","Safety Officer","Aerospace Education Officer","External Aerospace Education Officer","Internal Aerospace Education Officer","Communications Officer","Information Technology Officer","Cybersecurity / Cyber Education Officer","Web Security Administrator","Logistics Officer","Supply Officer","Transportation Officer","Aircraft Maintenance Officer","Vehicle Maintenance Officer","Finance Officer","Legal Officer","Government Relations Advisor","Marketing & Communications Officer","Health Services Officer","Safety Officer","Homeland Security Officer","Counterdrug Officer","Custom"];
const state={chart:{id:crypto.randomUUID(),title:"",subtitle:"",organizationName:"",chartType:"command",people:[],manualLinks:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},editingId:null,layout:{},linkStart:null};
const $=id=>document.getElementById(id);
const els={title:$("chartTitle"),subtitle:$("chartSubtitle"),org:$("orgName"),type:$("chartType"),form:$("personForm"),name:$("personName"),rank:$("personRank"),position:$("personPosition"),section:$("personSection"),email:$("personEmail"),phone:$("personPhone"),sup:$("personSupervisor"),cap:$("personCapTitle"),tbody:document.querySelector("#peopleTable tbody"),preview:$("chartPreview"),validation:$("validationOutput")};
CAP_TITLES.forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t||"CAP Title (optional)";els.cap.append(o)});
const touch=()=>state.chart.updatedAt=new Date().toISOString();
function syncMeta(){state.chart.title=els.title.value.trim();state.chart.subtitle=els.subtitle.value.trim();state.chart.organizationName=els.org.value.trim();state.chart.chartType=els.type.value;touch();render();}
[els.title,els.subtitle,els.org,els.type].forEach(e=>e.addEventListener("input",syncMeta));
const supName=id=>state.chart.people.find(p=>p.id===id)?.name||"—";
function populateSupervisor(){els.sup.innerHTML="<option value=''>Supervisor (root)</option>";state.chart.people.forEach(p=>{const o=document.createElement("option");o.value=p.id;o.textContent=`${p.rank?`${p.rank} `:""}${p.name}`;els.sup.append(o)});}
function renderTable(){els.tbody.innerHTML="";state.chart.people.forEach(p=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${p.name}</td><td>${p.rank||""}</td><td>${p.position}</td><td>${p.section||""}</td><td>${supName(p.supervisorId)}</td><td><button data-act='edit' data-id='${p.id}'>Edit</button> <button data-act='del' data-id='${p.id}'>Delete</button></td>`;els.tbody.append(tr)})}
function nodeCard(p){const init=(p.name||"?").split(" ").map(v=>v[0]).join("").slice(0,3).toUpperCase();return `<div class='card'><div class='badge'>${init}</div><div class='rank'>${p.rank||""}</div><div class='name'>${p.name}</div><div class='position'>${p.position}</div><div class='section'>${p.section||""}</div><button class='link-btn' data-link='${p.id}' type='button'>Link</button></div>`}
function treeHTML(parentId=null){const children=state.chart.people.filter(p=>(p.supervisorId||null)===parentId).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)||a.name.localeCompare(b.name));if(!children.length)return"";return `<ul>${children.map(c=>`<li draggable='true' data-person='${c.id}'><div class='node-wrap' data-node='${c.id}'>${nodeCard(c)}</div>${treeHTML(c.id)}</li>`).join("")}</ul>`;}
function renderLinks(){const svg=els.preview.querySelector(".manual-links");if(!svg)return;svg.innerHTML="";const r=els.preview.getBoundingClientRect();state.chart.manualLinks=(state.chart.manualLinks||[]).filter(l=>state.layout[l.from]&&state.layout[l.to]);for(const l of state.chart.manualLinks){const a=state.layout[l.from],b=state.layout[l.to];const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",a.x-r.left);line.setAttribute("y1",a.y-r.top);line.setAttribute("x2",b.x-r.left);line.setAttribute("y2",b.y-r.top);line.setAttribute("stroke","#e06f00");line.setAttribute("stroke-width","2");line.setAttribute("marker-end","url(#arrow)");svg.append(line);} }
function captureNodePositions(){state.layout={};els.preview.querySelectorAll("[data-node]").forEach(el=>{const id=el.dataset.node,rect=el.querySelector('.card').getBoundingClientRect();state.layout[id]={x:rect.left+rect.width/2,y:rect.top+rect.height/2};});}
function render(){populateSupervisor();renderTable();const styleClass=`style-${state.chart.chartType}`;els.preview.innerHTML=`<svg class='manual-links'><defs><marker id='arrow' markerWidth='10' markerHeight='7' refX='10' refY='3.5' orient='auto'><polygon points='0 0, 10 3.5, 0 7' fill='#e06f00'/></marker></defs></svg><div class='org-tree ${styleClass}'><h3>${state.chart.title||"Untitled Chart"}</h3><small>${state.chart.subtitle||""} ${state.chart.organizationName?`• ${state.chart.organizationName}`:""}</small>${treeHTML(null)}</div>`;attachDnD();attachPreviewInteractions();captureNodePositions();renderLinks();}
function upsertPerson(e){e.preventDefault();const name=els.name.value.trim(),position=els.position.value.trim();if(!name||!position)return;if(els.cap.value&&els.cap.value!=="Custom")els.position.value=els.cap.value;const payload={id:state.editingId||crypto.randomUUID(),name,rank:els.rank.value.trim(),position:els.position.value.trim(),section:els.section.value.trim(),email:els.email.value.trim(),phone:els.phone.value.trim(),supervisorId:els.sup.value||null,sortOrder:Date.now()};if(state.editingId){state.chart.people=state.chart.people.map(p=>p.id===state.editingId?payload:p);state.editingId=null;$("personSubmit").textContent="Add Person";}else state.chart.people.push(payload);e.target.reset();touch();render();}
els.form.addEventListener("submit",upsertPerson);
els.tbody.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;const id=b.dataset.id;const p=state.chart.people.find(x=>x.id===id);if(b.dataset.act==="del"){state.chart.people=state.chart.people.filter(x=>x.id!==id).map(x=>x.supervisorId===id?{...x,supervisorId:null}:x);state.chart.manualLinks=(state.chart.manualLinks||[]).filter(l=>l.from!==id&&l.to!==id);touch();render();}else if(p){state.editingId=id;els.name.value=p.name;els.rank.value=p.rank||"";els.position.value=p.position;els.section.value=p.section||"";els.email.value=p.email||"";els.phone.value=p.phone||"";els.sup.value=p.supervisorId||"";$("personSubmit").textContent="Update Person";}});
function detectCycle(){const map=Object.fromEntries(state.chart.people.map(p=>[p.id,p.supervisorId]));for(const p of state.chart.people){let seen=new Set([p.id]);let cur=map[p.id];while(cur){if(seen.has(cur))return true;seen.add(cur);cur=map[cur];}}return false;}
$("validateBtn").onclick=()=>{const names=state.chart.people.map(p=>p.name.toLowerCase());const dup=names.find((n,i)=>names.indexOf(n)!==i);const roots=state.chart.people.filter(p=>!p.supervisorId);const noSup=state.chart.people.filter(p=>p.supervisorId===null).length!==1&&state.chart.people.length>1;const cyc=detectCycle();els.validation.textContent=dup?`Duplicate name: ${dup}`:cyc?"Circular relationship detected":roots.length<1?"At least one root required":noSup?"More than one root found (allowed, but check command structure).":"Validation passed."};
function download(name,blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);} 
function exportSVG(){const footer=`Generated ${new Date().toLocaleString()}`;const content=els.preview.innerHTML.replace("</div>",`<p>${footer}</p></div>`);const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='2200' height='1400'><foreignObject width='100%' height='100%'><div xmlns='http://www.w3.org/1999/xhtml' style='font-family:Arial;padding:12px'>${content}</div></foreignObject></svg>`;download(`${(state.chart.title||"org-chart").replace(/\s+/g,"-")}.svg`,new Blob([svg],{type:"image/svg+xml"}));return svg;}
$("exportSvgBtn").onclick=exportSVG;
$("exportPngBtn").onclick=()=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.width;c.height=img.height;c.getContext("2d").drawImage(img,0,0);c.toBlob(b=>download("org-chart.png",b));};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(exportSVG());};
$("exportPdfBtn").onclick=()=>{const w=window.open("","_blank");w.document.write(`<html><body><h2>${state.chart.title||"Org Chart"}</h2>${els.preview.innerHTML}<footer>Generated ${new Date().toLocaleString()} • Letter/Tabloid friendly</footer><script>window.print()<\/script></body></html>`);w.document.close();};
$("saveJsonBtn").onclick=()=>download("org-chart.json",new Blob([JSON.stringify(state.chart,null,2)],{type:"application/json"}));
$("loadJsonInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{state.chart=JSON.parse(r.result);state.chart.manualLinks=state.chart.manualLinks||[];els.title.value=state.chart.title||"";els.subtitle.value=state.chart.subtitle||"";els.org.value=state.chart.organizationName||"";els.type.value=state.chart.chartType||"command";render();};r.readAsText(f)};
function normalizeRow(row){const g=(...keys)=>keys.map(k=>row[k]??row[k.toLowerCase()]??row[k.toUpperCase()]).find(v=>v!==undefined&&v!==null&&`${v}`.trim()!=="")||"";return {name:`${g("name","full name","member")}`.trim(),rank:`${g("rank","grade")}`.trim(),position:`${g("position","duty position","title")}`.trim()||"Member",section:`${g("section","department","unit")}`.trim(),email:`${g("email","mail")}`.trim(),phone:`${g("phone","cell")}`.trim(),supervisorName:`${g("supervisorName","supervisor","reportsTo")}`.trim()};}
function importRows(rows){const added=rows.map(r=>normalizeRow(r)).filter(r=>r.name).map(row=>({id:crypto.randomUUID(),name:row.name,rank:row.rank,position:row.position,section:row.section,email:row.email,phone:row.phone,supervisorId:null,sortOrder:Date.now()+Math.random(),_sup:row.supervisorName}));state.chart.people.push(...added);added.forEach(p=>{if(p._sup){const sup=state.chart.people.find(x=>x.name.toLowerCase()===p._sup.toLowerCase());if(sup)p.supervisorId=sup.id;}delete p._sup;});touch();render();}
$("importCsvInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const lines=r.result.split(/\r?\n/).filter(Boolean);const headers=lines.shift().split(",").map(h=>h.trim());importRows(lines.map(l=>Object.fromEntries(l.split(",").map((v,i)=>[headers[i],v?.trim()||""]))));};r.readAsText(f)};
$("importExcelInput").onchange=async e=>{const f=e.target.files[0];if(!f||!window.XLSX)return;const buf=await f.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];importRows(XLSX.utils.sheet_to_json(ws,{defval:""}));};
$("duplicateBtn").onclick=()=>{state.chart={...structuredClone(state.chart),id:crypto.randomUUID(),title:`${state.chart.title||"Chart"} (Copy)`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};render();};
$("clearBtn").onclick=()=>{if(confirm("Clear all people and settings?")){state.chart={id:crypto.randomUUID(),title:"",subtitle:"",organizationName:"",chartType:"command",people:[],manualLinks:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};els.title.value=els.subtitle.value=els.org.value="";els.type.value="command";render();}};
document.querySelectorAll("[data-template]").forEach(b=>b.onclick=()=>applyTemplate(b.dataset.template));
function applyTemplate(t){const templates={squadron:[['Cmdr','Commander',null],['DC','Deputy Commander','Cmdr'],['PAO','Public Affairs Officer','Cmdr'],['Safety','Safety Officer','Cmdr']],encampment:[['Cmd','Commander',null],['COS','Chief of Staff','Cmd'],['Ops','Operations','COS']],conference:[['Dir','Director',null],['Program','Program Lead','Dir'],['Logistics','Logistics Officer','Dir']],cadet:[['Cadet Cmdr','Cadet Commander',null],['Flight A','Flight Commander','Cadet Cmdr'],['Flight B','Flight Commander','Cadet Cmdr']],ics:[['IC','Incident Commander',null],['PIO','Public Information Officer','IC'],['Log','Logistics Officer','IC']]};const rows=templates[t]||[];state.chart.people=[];state.chart.manualLinks=[];const byName={};rows.forEach(([name,pos])=>{const p={id:crypto.randomUUID(),name,position:pos,supervisorId:null,sortOrder:Date.now()+Math.random()};byName[name]=p;state.chart.people.push(p)});rows.forEach(([name,,sup])=>{if(sup)byName[name].supervisorId=byName[sup].id});touch();render();}
function attachDnD(){let dragged=null;els.preview.querySelectorAll('[data-person]').forEach(el=>{el.ondragstart=()=>dragged=el.dataset.person;el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const target=el.dataset.person;if(dragged&&dragged!==target){const p=state.chart.people.find(x=>x.id===dragged);p.supervisorId=target;touch();render();}}});}
function attachPreviewInteractions(){let drag=null;els.preview.querySelectorAll('.card').forEach(card=>{card.addEventListener('pointerdown',e=>{if(e.target.closest('.link-btn'))return;const node=card.closest('[data-node]');drag={id:node.dataset.node,startX:e.clientX,startY:e.clientY,orig:state.layout[node.dataset.node]};card.setPointerCapture(e.pointerId);});card.addEventListener('pointermove',e=>{if(!drag)return;const node=card.closest('[data-node]');const wrap=node;wrap.style.transform=`translate(${e.clientX-drag.startX}px,${e.clientY-drag.startY}px)`;});card.addEventListener('pointerup',e=>{if(!drag)return;const node=card.closest('[data-node]');const dX=e.clientX-drag.startX,dY=e.clientY-drag.startY;node.style.transform=`translate(${dX}px,${dY}px)`;state.layout[drag.id]={x:drag.orig.x+dX,y:drag.orig.y+dY};drag=null;renderLinks();});});els.preview.querySelectorAll('.link-btn').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.link;if(!state.linkStart){state.linkStart=id;btn.textContent='Pick target';return;}if(state.linkStart!==id){state.chart.manualLinks.push({from:state.linkStart,to:id});touch();}state.linkStart=null;render();});}
$("themeToggle").onclick=()=>document.body.classList.toggle("dark");$("presentationToggle").onclick=()=>document.body.classList.toggle("presentation");$("printModeToggle").onclick=()=>document.body.classList.toggle("print");
render();
